<?php

$sources = [
	// "countries" => get_param_countries($uri),
	"active" => [
		"Inactive",	"Active", "Completed"
	],

	"increment" => [
		"-"=>"Deduct",	"+"=>"Add Interest"
	],

	"lock_duration" => "7 days",
	"publish" => [
		"Draft", "Publish"
	],

	"account_types"=>[
		"SAVINGS" => "Savings Account",
		"CURRENT" => "Current Account",
	],
	"confirm" => [
		"Pending", "Confirmed"
	],

	"condition" => [
		"Poor", "Fair", "Good", "Excellent"
	],

	"approval" => [
		"Unapproved", "Approved"
	],
	
	"approval2" => [
		"Unapproved", "Approved"
	],

	"status" => [
		"Inactive", "Active", "Paused", "Completed"
	],

	"bool" => [
		"No", "Yes"
	],

	"onoff" => [
		"Unlock Account", "Lock Account"
	],
	"approval" => [
		"Unapproved", "Approved"
	],

	"accessLevel" => [
		"View Access", "Creation Access", "Modification Access", "Full Access"
	],

	"datatypes" => [
		'picture'=>['gif','jpg','bmp','jpeg','png','svg','webp'],
		'audio'=>['mp3','wma','m4a','ogg'],
		'document'=>['doc','docx','txt','pdf','xls','xlsx'],
		'video'=>['mp4','avi','3pg','mkv','wmv'],
		'pdf'=>['pdf'],
		'archive'=>['zip','7z','rar','exe']
	],

	"gender" => [
		"m"=>"Male", "f"=>"Female"
	],

	"transaction_type" => [
		"credit"=>"Credit", "debit"=>"Debit"
	],

	"account_type" => [
		"current"=>"Current", "savings"=>"Savings"
	],

	"mode_of_payment" => [
		"cash"=>"Cash", "cheque"=>"Cheque", "card"=>"Card Payment", "transfer"=>"Mobile Transfer"
	],

	"user-category" => [
		1=>"Admin User",
		2=>"Regular Member",
	],
	"banks"=>[
		"063"=>"Access Bank Plc (Diamond)",
		"050"=>"Ecobank Nigeria",
		"084"=>"Enterprise Bank Plc",
		"070"=>"Fidelity Bank Plc",
		"011"=>"First Bank of Nigeria Plc",
		"214"=>"First City Monument Bank",
		"058"=>"Guaranty Trust Bank Plc",
		"030"=>"Heritage Bank",
		"301"=>"Jaiz Bank",
		"082"=>"Keystone Bank Ltd",
		"014"=>"Mainstreet Bank Plc",
		"076"=>"Polaris Bank",
		"039"=>"Stanbic IBTC Plc",
		"232"=>"Sterling Bank Plc",
		"032"=>"Union Bank Nigeria Plc",
		"033"=>"United Bank for Africa Plc",
		"215"=>"Unity Bank Plc",
		"035"=>"WEMA Bank Plc",
		"057"=>"Zenith Bank International",
	],
	"states"=>[
		"abia"=>"Abia State",
		 "adamawa"=>"Adamawa State",
		 "akwa-ibom"=>"Akwa Ibom State",
		 "anambra"=>"Anambra State",
		 "bauchi"=>"Bauchi State",
		 "bayelsa"=>"Bayelsa State",
		 "benue"=>"Benue State",
		 "borno"=>"Borno State",
		 "cross-river"=>"Cross River State",
		 "delta"=>"Delta State",
		 "ebonyi"=>"Ebonyi State",
		 "edo"=>"Edo State",
		 "ekiti"=>"Ekiti State",
		 "enugu"=>"Enugu State",
		 "fct-abuja"=>"FCT - Abuja",
		 "gombe"=>"Gombe State",
		 "imo"=>"Imo State",
		 "jigawa"=>"Jigawa State",
		 "kano"=>"Kano State",
		 "katsina"=>"Katsina State",
		 "kebbi"=>"Kebbi State",
		 "kogi"=>"Kogi State",
		 "kwara"=>"Kwara State",
		 "lagos"=>"Lagos State",
		 "nasarawa"=>"Nasarawa State",
		 "niger"=>"Niger State",
		 "ogun"=>"Ogun State",
		 "ondo"=>"Ondo State",
		 "osun"=>"Osun State",
		 "oyo"=>"Oyo State",
		 "plateau"=>"Plateau State",
		 "rivers"=>"Rivers State",
		 "sokoto"=>"Sokoto State",
		 "taraba"=>"Taraba State",
		 "yobe"=>"Yobe State",
		 "zamfara"=>"Zamfara State"
	],

	"countries" => [
		"AF" => "Afghanistan",
		"AL" => "Albania",
		"DZ" => "Algeria",
		"AS" => "American Samoa",
		"AD" => "Andorra",
		"AO" => "Angola",
		"AI" => "Anguilla",
		"AQ" => "Antarctica",
		"AG" => "Antigua and Barbuda",
		"AR" => "Argentina",
		"AM" => "Armenia",
		"AW" => "Aruba",
		"AU" => "Australia",
		"AT" => "Austria",
		"AZ" => "Azerbaijan",
		"BS" => "Bahamas",
		"BH" => "Bahrain",
		"BD" => "Bangladesh",
		"BB" => "Barbados",
		"BY" => "Belarus",
		"BE" => "Belgium",
		"BZ" => "Belize",
		"BJ" => "Benin",
		"BM" => "Bermuda",
		"BT" => "Bhutan",
		"BO" => "Bolivia",
		"BA" => "Bosnia and Herzegovina",
		"BW" => "Botswana",
		"BV" => "Bouvet Island",
		"BR" => "Brazil",
		"BQ" => "British Antarctic Territory",
		"IO" => "British Indian Ocean Territory",
		"VG" => "British Virgin Islands",
		"BN" => "Brunei",
		"BG" => "Bulgaria",
		"BF" => "Burkina Faso",
		"BI" => "Burundi",
		"KH" => "Cambodia",
		"CM" => "Cameroon",
		"CA" => "Canada",
		"CT" => "Canton and Enderbury Islands",
		"CV" => "Cape Verde",
		"KY" => "Cayman Islands",
		"CF" => "Central African Republic",
		"TD" => "Chad",
		"CL" => "Chile",
		"CN" => "China",
		"CX" => "Christmas Island",
		"CC" => "Cocos [Keeling] Islands",
		"CO" => "Colombia",
		"KM" => "Comoros",
		"CG" => "Congo - Brazzaville",
		"CD" => "Congo - Kinshasa",
		"CK" => "Cook Islands",
		"CR" => "Costa Rica",
		"HR" => "Croatia",
		"CU" => "Cuba",
		"CY" => "Cyprus",
		"CZ" => "Czech Republic",
		"CI" => "Côte d’Ivoire",
		"DK" => "Denmark",
		"DJ" => "Djibouti",
		"DM" => "Dominica",
		"DO" => "Dominican Republic",
		"NQ" => "Dronning Maud Land",
		"DD" => "East Germany",
		"EC" => "Ecuador",
		"EG" => "Egypt",
		"SV" => "El Salvador",
		"GQ" => "Equatorial Guinea",
		"ER" => "Eritrea",
		"EE" => "Estonia",
		"ET" => "Ethiopia",
		"FK" => "Falkland Islands",
		"FO" => "Faroe Islands",
		"FJ" => "Fiji",
		"FI" => "Finland",
		"FR" => "France",
		"GF" => "French Guiana",
		"PF" => "French Polynesia",
		"TF" => "French Southern Territories",
		"FQ" => "French Southern and Antarctic Territories",
		"GA" => "Gabon",
		"GM" => "Gambia",
		"GE" => "Georgia",
		"DE" => "Germany",
		"GH" => "Ghana",
		"GI" => "Gibraltar",
		"GR" => "Greece",
		"GL" => "Greenland",
		"GD" => "Grenada",
		"GP" => "Guadeloupe",
		"GU" => "Guam",
		"GT" => "Guatemala",
		"GG" => "Guernsey",
		"GN" => "Guinea",
		"GW" => "Guinea-Bissau",
		"GY" => "Guyana",
		"HT" => "Haiti",
		"HM" => "Heard Island and McDonald Islands",
		"HN" => "Honduras",
		"HK" => "Hong Kong SAR China",
		"HU" => "Hungary",
		"IS" => "Iceland",
		"IN" => "India",
		"ID" => "Indonesia",
		"IR" => "Iran",
		"IQ" => "Iraq",
		"IE" => "Ireland",
		"IM" => "Isle of Man",
		"IL" => "Israel",
		"IT" => "Italy",
		"JM" => "Jamaica",
		"JP" => "Japan",
		"JE" => "Jersey",
		"JT" => "Johnston Island",
		"JO" => "Jordan",
		"KZ" => "Kazakhstan",
		"KE" => "Kenya",
		"KI" => "Kiribati",
		"KW" => "Kuwait",
		"KG" => "Kyrgyzstan",
		"LA" => "Laos",
		"LV" => "Latvia",
		"LB" => "Lebanon",
		"LS" => "Lesotho",
		"LR" => "Liberia",
		"LY" => "Libya",
		"LI" => "Liechtenstein",
		"LT" => "Lithuania",
		"LU" => "Luxembourg",
		"MO" => "Macau SAR China",
		"MK" => "Macedonia",
		"MG" => "Madagascar",
		"MW" => "Malawi",
		"MY" => "Malaysia",
		"MV" => "Maldives",
		"ML" => "Mali",
		"MT" => "Malta",
		"MH" => "Marshall Islands",
		"MQ" => "Martinique",
		"MR" => "Mauritania",
		"MU" => "Mauritius",
		"YT" => "Mayotte",
		"FX" => "Metropolitan France",
		"MX" => "Mexico",
		"FM" => "Micronesia",
		"MI" => "Midway Islands",
		"MD" => "Moldova",
		"MC" => "Monaco",
		"MN" => "Mongolia",
		"ME" => "Montenegro",
		"MS" => "Montserrat",
		"MA" => "Morocco",
		"MZ" => "Mozambique",
		"MM" => "Myanmar [Burma]",
		"NA" => "Namibia",
		"NR" => "Nauru",
		"NP" => "Nepal",
		"NL" => "Netherlands",
		"AN" => "Netherlands Antilles",
		"NT" => "Neutral Zone",
		"NC" => "New Caledonia",
		"NZ" => "New Zealand",
		"NI" => "Nicaragua",
		"NE" => "Niger",
		"NG" => "Nigeria",
		"NU" => "Niue",
		"NF" => "Norfolk Island",
		"KP" => "North Korea",
		"VD" => "North Vietnam",
		"MP" => "Northern Mariana Islands",
		"NO" => "Norway",
		"OM" => "Oman",
		"PC" => "Pacific Islands Trust Territory",
		"PK" => "Pakistan",
		"PW" => "Palau",
		"PS" => "Palestinian Territories",
		"PA" => "Panama",
		"PZ" => "Panama Canal Zone",
		"PG" => "Papua New Guinea",
		"PY" => "Paraguay",
		"YD" => "People's Democratic Republic of Yemen",
		"PE" => "Peru",
		"PH" => "Philippines",
		"PN" => "Pitcairn Islands",
		"PL" => "Poland",
		"PT" => "Portugal",
		"PR" => "Puerto Rico",
		"QA" => "Qatar",
		"RO" => "Romania",
		"RU" => "Russia",
		"RW" => "Rwanda",
		"RE" => "Réunion",
		"BL" => "Saint Barthélemy",
		"SH" => "Saint Helena",
		"KN" => "Saint Kitts and Nevis",
		"LC" => "Saint Lucia",
		"MF" => "Saint Martin",
		"PM" => "Saint Pierre and Miquelon",
		"VC" => "Saint Vincent and the Grenadines",
		"WS" => "Samoa",
		"SM" => "San Marino",
		"SA" => "Saudi Arabia",
		"SN" => "Senegal",
		"RS" => "Serbia",
		"CS" => "Serbia and Montenegro",
		"SC" => "Seychelles",
		"SL" => "Sierra Leone",
		"SG" => "Singapore",
		"SK" => "Slovakia",
		"SI" => "Slovenia",
		"SB" => "Solomon Islands",
		"SO" => "Somalia",
		"ZA" => "South Africa",
		"GS" => "South Georgia and the South Sandwich Islands",
		"KR" => "South Korea",
		"ES" => "Spain",
		"LK" => "Sri Lanka",
		"SD" => "Sudan",
		"SR" => "Suriname",
		"SJ" => "Svalbard and Jan Mayen",
		"SZ" => "Swaziland",
		"SE" => "Sweden",
		"CH" => "Switzerland",
		"SY" => "Syria",
		"ST" => "São Tomé and Príncipe",
		"TW" => "Taiwan",
		"TJ" => "Tajikistan",
		"TZ" => "Tanzania",
		"TH" => "Thailand",
		"TL" => "Timor-Leste",
		"TG" => "Togo",
		"TK" => "Tokelau",
		"TO" => "Tonga",
		"TT" => "Trinidad and Tobago",
		"TN" => "Tunisia",
		"TR" => "Turkey",
		"TM" => "Turkmenistan",
		"TC" => "Turks and Caicos Islands",
		"TV" => "Tuvalu",
		"UM" => "U.S. Minor Outlying Islands",
		"PU" => "U.S. Miscellaneous Pacific Islands",
		"VI" => "U.S. Virgin Islands",
		"UG" => "Uganda",
		"UA" => "Ukraine",
		"SU" => "Union of Soviet Socialist Republics",
		"AE" => "United Arab Emirates",
		"GB" => "United Kingdom",
		"US" => "United States",
		"ZZ" => "Unknown or Invalid Region",
		"UY" => "Uruguay",
		"UZ" => "Uzbekistan",
		"VU" => "Vanuatu",
		"VA" => "Vatican City",
		"VE" => "Venezuela",
		"VN" => "Vietnam",
		"WK" => "Wake Island",
		"WF" => "Wallis and Futuna",
		"EH" => "Western Sahara",
		"YE" => "Yemen",
		"ZM" => "Zambia",
		"ZW" => "Zimbabwe",
		"AX" => "Åland Islands",
	],

	"currency" => [
		"AFA" => "Afghan Afghani",
		"ALL" => "Albanian Lek",
		"DZD" => "Algerian Dinar",
		"AOA" => "Angolan Kwanza",
		"ARS" => "Argentine Peso",
		"AMD" => "Armenian Dram",
		"AWG" => "Aruban Florin",
		"AUD" => "Australian Dollar",
		"AZN" => "Azerbaijani Manat",
		"BSD" => "Bahamian Dollar",
		"BHD" => "Bahraini Dinar",
		"BDT" => "Bangladeshi Taka",
		"BBD" => "Barbadian Dollar",
		"BYR" => "Belarusian Ruble",
		"BEF" => "Belgian Franc",
		"BZD" => "Belize Dollar",
		"BMD" => "Bermudan Dollar",
		"BTN" => "Bhutanese Ngultrum",
		"BTC" => "Bitcoin",
		"BOB" => "Bolivian Boliviano",
		"BAM" => "Bosnia",
		"BWP" => "Botswanan Pula",
		"BRL" => "Brazilian Real",
		"GBP" => "British Pound Sterling",
		"BND" => "Brunei Dollar",
		"BGN" => "Bulgarian Lev",
		"BIF" => "Burundian Franc",
		"KHR" => "Cambodian Riel",
		"CAD" => "Canadian Dollar",
		"CVE" => "Cape Verdean Escudo",
		"KYD" => "Cayman Islands Dollar",
		"XOF" => "CFA Franc BCEAO",
		"XAF" => "CFA Franc BEAC",
		"XPF" => "CFP Franc",
		"CLP" => "Chilean Peso",
		"CNY" => "Chinese Yuan",
		"COP" => "Colombian Peso",
		"KMF" => "Comorian Franc",
		"CDF" => "Congolese Franc",
		"CRC" => "Costa Rican ColÃ³n",
		"HRK" => "Croatian Kuna",
		"CUC" => "Cuban Convertible Peso",
		"CZK" => "Czech Republic Koruna",
		"DKK" => "Danish Krone",
		"DJF" => "Djiboutian Franc",
		"DOP" => "Dominican Peso",
		"XCD" => "East Caribbean Dollar",
		"EGP" => "Egyptian Pound",
		"ERN" => "Eritrean Nakfa",
		"EEK" => "Estonian Kroon",
		"ETB" => "Ethiopian Birr",
		"EUR" => "Euro",
		"FKP" => "Falkland Islands Pound",
		"FJD" => "Fijian Dollar",
		"GMD" => "Gambian Dalasi",
		"GEL" => "Georgian Lari",
		"DEM" => "German Mark",
		"GHS" => "Ghanaian Cedi",
		"GIP" => "Gibraltar Pound",
		"GRD" => "Greek Drachma",
		"GTQ" => "Guatemalan Quetzal",
		"GNF" => "Guinean Franc",
		"GYD" => "Guyanaese Dollar",
		"HTG" => "Haitian Gourde",
		"HNL" => "Honduran Lempira",
		"HKD" => "Hong Kong Dollar",
		"HUF" => "Hungarian Forint",
		"ISK" => "Icelandic KrÃ³na",
		"INR" => "Indian Rupee",
		"IDR" => "Indonesian Rupiah",
		"IRR" => "Iranian Rial",
		"IQD" => "Iraqi Dinar",
		"ILS" => "Israeli New Sheqel",
		"ITL" => "Italian Lira",
		"JMD" => "Jamaican Dollar",
		"JPY" => "Japanese Yen",
		"JOD" => "Jordanian Dinar",
		"KZT" => "Kazakhstani Tenge",
		"KES" => "Kenyan Shilling",
		"KWD" => "Kuwaiti Dinar",
		"KGS" => "Kyrgystani Som",
		"LAK" => "Laotian Kip",
		"LVL" => "Latvian Lats",
		"LBP" => "Lebanese Pound",
		"LSL" => "Lesotho Loti",
		"LRD" => "Liberian Dollar",
		"LYD" => "Libyan Dinar",
		"LTL" => "Lithuanian Litas",
		"MOP" => "Macanese Pataca",
		"MKD" => "Macedonian Denar",
		"MGA" => "Malagasy Ariary",
		"MWK" => "Malawian Kwacha",
		"MYR" => "Malaysian Ringgit",
		"MVR" => "Maldivian Rufiyaa",
		"MRO" => "Mauritanian Ouguiya",
		"MUR" => "Mauritian Rupee",
		"MXN" => "Mexican Peso",
		"MDL" => "Moldovan Leu",
		"MNT" => "Mongolian Tugrik",
		"MAD" => "Moroccan Dirham",
		"MZM" => "Mozambican Metical",
		"MMK" => "Myanmar Kyat",
		"NAD" => "Namibian Dollar",
		"NPR" => "Nepalese Rupee",
		"ANG" => "Netherlands Antillean Guilder",
		"TWD" => "New Taiwan Dollar",
		"NZD" => "New Zealand Dollar",
		"NIO" => "Nicaraguan CÃ³rdoba",
		"NGN" => "Nigerian Naira",
		"KPW" => "North Korean Won",
		"NOK" => "Norwegian Krone",
		"OMR" => "Omani Rial",
		"PKR" => "Pakistani Rupee",
		"PAB" => "Panamanian Balboa",
		"PGK" => "Papua New Guinean Kina",
		"PYG" => "Paraguayan Guarani",
		"PEN" => "Peruvian Nuevo Sol",
		"PHP" => "Philippine Peso",
		"PLN" => "Polish Zloty",
		"QAR" => "Qatari Rial",
		"RON" => "Romanian Leu",
		"RUB" => "Russian Ruble",
		"RWF" => "Rwandan Franc",
		"SVC" => "Salvadoran ColÃ³n",
		"WST" => "Samoan Tala",
		"SAR" => "Saudi Riyal",
		"RSD" => "Serbian Dinar",
		"SCR" => "Seychellois Rupee",
		"SLL" => "Sierra Leonean Leone",
		"SGD" => "Singapore Dollar",
		"SKK" => "Slovak Koruna",
		"SBD" => "Solomon Islands Dollar",
		"SOS" => "Somali Shilling",
		"ZAR" => "South African Rand",
		"KRW" => "South Korean Won",
		"XDR" => "Special Drawing Rights",
		"LKR" => "Sri Lankan Rupee",
		"SHP" => "St. Helena Pound",
		"SDG" => "Sudanese Pound",
		"SRD" => "Surinamese Dollar",
		"SZL" => "Swazi Lilangeni",
		"SEK" => "Swedish Krona",
		"CHF" => "Swiss Franc",
		"SYP" => "Syrian Pound",
		"STD" => "São Tomé and Príncipe Dobra",
		"TJS" => "Tajikistani Somoni",
		"TZS" => "Tanzanian Shilling",
		"THB" => "Thai Baht",
		"TOP" => "Tongan pa'anga",
		"TTD" => "Trinidad & Tobago Dollar",
		"TND" => "Tunisian Dinar",
		"TRY" => "Turkish Lira",
		"TMT" => "Turkmenistani Manat",
		"UGX" => "Ugandan Shilling",
		"UAH" => "Ukrainian Hryvnia",
		"AED" => "United Arab Emirates Dirham",
		"UYU" => "Uruguayan Peso",
		"USD" => "US Dollar",
		"UZS" => "Uzbekistan Som",
		"VUV" => "Vanuatu Vatu",
		"VEF" => "Venezuelan BolÃvar",
		"VND" => "Vietnamese Dong",
		"YER" => "Yemeni Rial",
		"ZMK" => "Zambian Kwacha"
	],
];

?>
